name: application workflow


on:
  workflow_dispatch:
  push:
  pull_request:
    types:
      - opened
      - edited

    branches:
      - main
      - 'feature/**'

env:
  NODEJS_VERSION: '14.9.0'
  NODEJS_PATH: ~/.npm
  NODEJS_KEY: node-modules-${{ hashFiles('**/package-lock.json') }}

jobs:
  lint:
    runs-on: macos-12
    steps:
      - name: Get application code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3

        with:
          node-version: ${{ env.NODEJS_VERSION }}
          path: ${{ env.NODEJS_PATH }}
          key:  ${{ env.NODEJS_KEY }}

      - run: npm ci
      - run: npm run lint

  test:
    needs: lint
    runs-on: macos-12
    steps:
      - name: Get application code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3

        with:
          node-version: ${{ env.NODEJS_VERSION }}
          path: ${{ env.NODEJS_PATH }}
          key: ${{ env.NODEJS_KEY }}

      - run: npm ci
      - run: npm run test
