name: application workflow


on:
  workflow_dispatch:
  push:
  pull_request:
    types:
      - opened
      - edited

    branches:
      - main
      - 'feature/**'

env:
  NODEJS_VERSION: '14.9.0'

jobs:
  lint:
    runs-on: macos-12
    steps:
      - name: Get application code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3

        with:
          node-version: "${{ env.NODEJS_VERSION }}"
          path: ~/.npm
          key:  node-modules-${{ hashFiles('**/package-lock.json') }}

      - run: npm install
      - run: npm run lint

  test:
    needs: lint
    runs-on: macos-12
    steps:
      - name: Get application code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3

        with:
          node-version: "${{ env.NODEJS_VERSION }}"
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      - run: npm install
      - run: npm run test
