name: application workflow


on:
  workflow_dispatch:
  push:
  pull_request:
    types:
      - opened
      - edited

    branches:
      - main
      - 'feature/**'

env:
  NODEJS_VERSION: '14.9.0'
  NODEJS_PATH: ~/.npm

jobs:
  lint:
    runs-on: macos-12
    steps:
      - name: Get application code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3

        with:
          node-version: ${{ env.NODEJS_VERSION }}
          path: ${{ env.NODEJS_PATH }}
          key:  node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint

  test:
    needs: lint
    runs-on: macos-12
    steps:
      - name: Get application code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3

        with:
          node-version: ${{ env.NODEJS_VERSION }}
          path: ${{ env.NODEJS_PATH }}
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test

  deployment:
    needs: test
    runs-on: macos-12
    environment: production
    steps:
      - name: Get application code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Download artifact
        uses: actions/upload-artifact@v3
