name: feature workflow

on:
  push:
    branches:
      - 'feature/**'

env:
  NODEJS_VERSION: '14.9.0'
  NODEJS_PATH: ~/.npm

jobs:
  lint:
    runs-on: macos-12

    steps:
      - name: Get application code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODEJS_VERSION }}
          path: ${{ env.NODEJS_PATH }}
          key:  node-modules-${{ hashFiles('**/package-lock.json') }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint

  test:
    needs: lint
    runs-on: macos-12

    steps:
      - name: Get application code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODEJS_VERSION }}
          path: ${{ env.NODEJS_PATH }}
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test

  build:
    needs: test
    runs-on: macos-12

    steps:
      - name: Get application code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODEJS_VERSION }}
          path: ${{ env.NODEJS_PATH }}
          key:  node-modules-${{ hashFiles('**/package-lock.json') }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
