name: main workflow


on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    types:
      - merged

env:
  NODEJS_VERSION: '14.9.0'
  NODEJS_PATH: ~/.npm

jobs:
#  lint:
#    runs-on: macos-12
#
#    steps:
#      - name: Get application code
#        uses: actions/checkout@v3
#        with:
#          token: ${{ github.token }}
#
#      - name: Cache dependencies
#        uses: actions/cache@v3
#        with:
#          path: ${{ env.NODEJS_PATH }}
#          key:  node-modules-${{ hashFiles('**/package-lock.json') }}
#
#      - name: Use Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: ${{ env.NODEJS_VERSION }}
#          cache: 'npm'
#
#      - name: Install dependencies
#        run: npm ci
#
#      - name: Run lint
#        run: npm run lint
#
#  test:
#    needs: lint
#    runs-on: macos-12
#
#    steps:
#      - name: Get application code
#        uses: actions/checkout@v3
#        with:
#          token: ${{ github.token }}
#
#      - name: Cache dependencies
#        uses: actions/cache@v3
#        with:
#          path: ${{ env.NODEJS_PATH }}
#          key:  node-modules-${{ hashFiles('**/package-lock.json') }}
#
#      - name: Use Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: ${{ env.NODEJS_VERSION }}
#          cache: 'npm'
#
#      - name: Install dependencies
#        run: npm ci
#
#      - name: Run tests
#        run: npm run test

  build:
#    needs: test
    runs-on: macos-12

    steps:
      - name: Get application code
        uses: actions/checkout@v3
        with:
          token: ${{ github.token }}

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.NODEJS_PATH }}
          key:  node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODEJS_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Download artifact
        uses: actions/upload-artifact@v3
        with:
          path: build
          name: build-files

  deploy:
    needs: build
#     if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged }}
    runs-on: macos-12

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Get build application
        uses: actions/download-artifact@v3
        with:
          name: build-files

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key:: ${{ github.token }}
          publish_dir: ./public
