name: main workflow

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
    types: [merged]

env:
  NODEJS_VERSION: '14.9.0'
  NODEJS_PATH: ~/.npm

jobs:
  lint:
     runs-on: macos-12
     steps:
       - name: Get application code
         uses: actions/checkout@v3
         with:
           token: ${{ github.token }}
       - name: Cache dependencies
         uses: actions/cache@v3
         with:
           path: ${{ env.NODEJS_PATH }}
           key:  node-modules-${{ hashFiles('**/package-lock.json') }}
       - name: Use Node.js
         uses: actions/setup-node@v3
         with:
           node-version: ${{ env.NODEJS_VERSION }}
           cache: 'npm'
       - name: Install dependencies
         run: npm ci
       - name: Run lint
         run: npm run lint

  test:
    needs: lint
    runs-on: macos-12
    steps:
       - name: Get application code
         uses: actions/checkout@v3
         with:
           token: ${{ github.token }}
       - name: Cache dependencies
         uses: actions/cache@v3
         with:
           path: ${{ env.NODEJS_PATH }}
           key:  node-modules-${{ hashFiles('**/package-lock.json') }}
       - name: Use Node.js
         uses: actions/setup-node@v3
         with:
           node-version: ${{ env.NODEJS_VERSION }}
           cache: 'npm'
       - name: Install dependencies
         run: npm ci
       - name: Run tests
         run: npm run test

  build:
    needs: test
    runs-on: macos-12

    steps:
      - name: Get application code
        uses: actions/checkout@v3
        with:
          token: ${{ github.token }}

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.NODEJS_PATH }}
          key:  node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODEJS_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Download artifact
        uses: actions/upload-artifact@v3
        with:
          path: build
          name: build-files

  deploy:
    needs: build
    runs-on: macos-12

    steps:
      - name: Get build application
        uses: actions/download-artifact@v3
        with:
          name: build-files
          path: public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: production
          publish_dir: ./public
